# build stage
FROM node:lts-alpine as buind-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#production satge
FROM nginx:stable-alpine as production-satge
EXPOSE 80
CMD ["nginx", "-g", "deamon off;"]